"use client";

import { BarChart3, BookOpen, CalendarDays, ChevronRight, Flag, Goal, TrendingUp } from "lucide-react";
import { useState } from "react";
import { AppShell } from "@/components/app-shell";
import { useBookloom } from "@/lib/local-store";

export default function StatsPage() {
  const { library, goals, addGoal } = useBookloom();
  const [showGoal, setShowGoal] = useState(false);
  const finished = library.filter((book) => book.status === "Finished");
  const average = finished.filter((book) => book.rating).reduce((sum, book) => sum + (book.rating ?? 0), 0) / Math.max(1, finished.filter((book) => book.rating).length);
  const currentGoal = goals[0];
  return <AppShell><div className="page-wrap"><div className="subpage-heading"><div><p className="eyebrow">Your reading year</p><h1>Stats & goals</h1><p className="lede">Patterns to notice, never numbers to feel guilty about.</p></div><button className="primary-button" onClick={() => setShowGoal(true)}><Goal size={17} /> New goal</button></div><div className="stats-cards"><div><BookOpen size={18} /><strong>{finished.length}</strong><span>books finished</span></div><div><BarChart3 size={18} /><strong>{average.toFixed(1)}</strong><span>average rating</span></div><div><TrendingUp size={18} /><strong>{library.filter((book) => book.status === "DNF").length}</strong><span>DNF, without guilt</span></div><div><CalendarDays size={18} /><strong>{library.reduce((sum, book) => sum + book.progress, 0)}</strong><span>progress points</span></div></div><div className="stats-grid"><section className="stats-panel"><div className="panel-heading"><div><p className="eyebrow">Reading goal · {currentGoal.year}</p><h2>{currentGoal.label}</h2></div><Flag size={20} color="var(--terracotta)" /></div><div className="goal-number"><strong>{currentGoal.current}</strong><span>/ {currentGoal.target} {currentGoal.unit}</span></div><div className="progress-track"><span style={{ width: `${Math.min(100, currentGoal.current / currentGoal.target * 100)}%` }} /></div><p className="stats-muted">{currentGoal.target - currentGoal.current} more {currentGoal.unit} at your own pace.</p></section><section className="stats-panel"><div className="panel-heading"><div><p className="eyebrow">Rating distribution</p><h2>What stays with you</h2></div><ChevronRight size={18} color="var(--sage)" /></div><div className="rating-bars">{[5, 4, 3, 2, 1].map((rating) => <div key={rating}><span>{rating} stars</span><div className="dna-track"><i style={{ width: `${rating === 5 ? 62 : rating === 4 ? 82 : rating === 3 ? 34 : 8}%` }} /></div><b>{rating === 5 ? 3 : rating === 4 ? 4 : rating === 3 ? 1 : 0}</b></div>)}</div></section></div>{showGoal && <div className="modal-backdrop" onClick={() => setShowGoal(false)}><form className="add-modal" onSubmit={(event) => { event.preventDefault(); addGoal({ label: "Books read", target: 30, current: 0, unit: "books", year: 2026 }); setShowGoal(false); }} onClick={(event) => event.stopPropagation()}><p className="eyebrow">Reading goal</p><h2>Make room for more pages.</h2><p className="modal-copy">Start with a gentle target. You can change it later.</p><button className="primary-button" type="submit"><Goal size={16} /> Create 30-book goal</button></form></div>}</div></AppShell>;
}
