"use client";

import { BarChart3, BookOpen, BriefcaseBusiness, Check, CircleDollarSign, Megaphone, Plus, ShieldCheck, Users } from "lucide-react";
import { useState } from "react";
import { AppShell } from "@/components/app-shell";

const sections = [{ label: "Overview", icon: BarChart3 }, { label: "Catalog", icon: BookOpen }, { label: "Campaigns", icon: Megaphone }, { label: "ARC", icon: Users }, { label: "Commerce", icon: CircleDollarSign }];

export default function ProfessionalPage() {
  const [active, setActive] = useState("Overview");
  const [created, setCreated] = useState(false);
  return <AppShell><div className="page-wrap"><div className="subpage-heading"><div><p className="eyebrow">Professional workspace</p><h1>Northwind Press</h1><p className="lede">Aggregate audience insight, declared clearly.</p></div><span className="verified-badge"><ShieldCheck size={15} /> Verified organization</span></div><div className="pro-layout"><aside className="pro-nav">{sections.map(({ label, icon: Icon }) => <button className={active === label ? "active" : ""} key={label} onClick={() => setActive(label)}><Icon size={16} /> {label}</button>)}<div className="pro-role"><BriefcaseBusiness size={15} /><span>Role</span><strong>Analytics</strong></div></aside><section className="pro-main"><div className="pro-header"><div><p className="eyebrow">{active}</p><h2>{active === "Overview" ? "A clearer view of your readers." : active}</h2></div><button className="primary-button" onClick={() => setCreated(true)}><Plus size={16} /> Create {active === "ARC" ? "ARC campaign" : "campaign"}</button></div>{active === "Overview" && <><div className="pro-metrics"><div><strong>1,284</strong><span>readers in aggregate</span></div><div><strong>62%</strong><span>prefer character-driven fiction</span></div><div><strong>84%</strong><span>completion rate</span></div><div><strong>0</strong><span>individual profiles exposed</span></div></div><div className="pro-callout"><ShieldCheck size={19} /><div><strong>Trust boundary active</strong><p>Professional data is aggregated with a minimum cohort threshold. Paid placement cannot modify ratings, Book DNA or organic ranking.</p></div></div></>}{active === "Catalog" && <div className="pro-table"><div><span>WORK</span><span>STATUS</span><span>ORGANIC SCORE</span></div><div><strong>The Left Hand of Darkness</strong><span className="status-pill">Claim pending</span><span>Community · 4.2</span></div><div><strong>Sea of Tranquility</strong><span className="status-pill">Cataloged</span><span>Community · 4.0</span></div></div>}{active === "Campaigns" && <div className="pro-table"><div><span>CAMPAIGN</span><span>STATUS</span><span>DISCLOSURE</span></div><div><strong>Autumn atmospheric reads</strong><span className="status-pill">Draft</span><span><Check size={13} /> Sponsored</span></div></div>}{active === "ARC" && <div className="pro-callout"><Users size={20} /><div><strong>ARC matching is opt-in</strong><p>Readers choose their preferred genres, formats and regions. Positive ratings are never required and reviews remain independent.</p></div></div>}{active === "Commerce" && <div className="pro-callout"><CircleDollarSign size={20} /><div><strong>Affiliate disclosure</strong><p>Commerce links will be clearly labeled. Prices and availability appear only when a configured provider returns them.</p></div></div>}</section></div>{created && <div className="toast-message">Draft created locally. It is not live or sponsored until approved.</div>}</div></AppShell>;
}
