import Link from "next/link";
import { ArrowLeft, Bookmark, BookOpen, Check, ChevronDown, Heart, Sparkles, Star } from "lucide-react";
import { AppShell } from "@/components/app-shell";

export default async function BookDetailPage({ params }: { params: Promise<{ provider: string; id: string }> }) {
  const { provider, id } = await params;
  const title = decodeURIComponent(id).replaceAll("-", " ");
  const displayTitle = title.replace(/\b\w/g, (letter) => letter.toUpperCase());

  return <AppShell><div className="page-wrap book-detail-page"><Link className="back-link" href="/explore"><ArrowLeft size={16} /> Back to explore</Link><section className="book-detail-hero"><div className="detail-cover"><span>Bookloom edition</span><strong>{displayTitle}</strong><small>Selected from {provider}</small></div><div className="detail-copy"><p className="eyebrow">Book detail · {provider}</p><h1>{displayTitle}</h1><p className="detail-author">A story waiting to become part of your reading life.</p><div className="detail-rating"><span><Star size={16} fill="currentColor" /> 4.2 community rating</span><span>1,284 readers</span></div><div className="detail-actions"><button className="primary-button"><BookOpen size={17} /> Want to read</button><button className="secondary-button"><Bookmark size={16} /> Save</button><button className="icon-button" aria-label="Add to favorites"><Heart size={17} /></button></div><div className="edition-picker"><span>Edition</span><button>Paperback · English <ChevronDown size={15} /></button></div></div></section><section className="detail-columns"><div><div className="detail-section"><p className="eyebrow">About this book</p><h2>A book with room to stay.</h2><p className="detail-description">The most useful book pages tell you more than a star average. Here you will find the work, its available editions, and the qualities readers noticed along the way.</p></div><div className="detail-section"><p className="eyebrow">Reader notes</p><div className="spoiler-safe"><Check size={16} /><span>Spoiler-safe by default</span></div></div></div><aside className="detail-aside"><div className="detail-section dna-detail"><div className="detail-section-heading"><div><p className="eyebrow">Book DNA</p><h2>How it feels</h2></div><Sparkles size={18} color="var(--sage)" /></div>{["Atmospheric", "Character-driven", "Thought-provoking", "Slow-burn"].map((trait, index) => <div className="dna-detail-row" key={trait}><span>{trait}</span><div className="dna-track"><i style={{ width: `${88 - index * 7}%` }} /></div><b>{88 - index * 7}</b></div>)}<small className="confidence-note">Based on 128 reader signals · High confidence</small></div><div className="detail-section where-to-get"><p className="eyebrow">Where to get it</p><h2>Choose your edition</h2><p>Availability and prices will appear here when a commerce provider is connected.</p></div></aside></section></div></AppShell>;
}
